# Table Name mappings
tables:
  campus: cim_hrdb_campus
  region: cim_hrdb_region
  month: cim_stats_month
  prc: cim_stats_prc
  prcmethod: cim_stats_prcmethod
  semester: cim_stats_semester
  week: cim_stats_week
  weeklyreport: cim_stats_weeklyreport
  year: cim_stats_year
  country: cim_hrdb_country
  assignment: cim_hrdb_assignment
  status: cim_hrdb_assignmentstatus
  person: cim_hrdb_person
  staff: cim_hrdb_staff
  vieweraccessgroup: accountadmin_vieweraccessgroup
  
# Column Mappings
campus:
  id: campus_id
  description: campus_desc
  short_description: campus_shortDesc
  account_group_id: accountgroup_id
  region_id: region_id
  website: campus_website
  facebook_group: campus_facebookgroup
  gcx_namespace: campus_gcxnamespace
  #province_id: province_id
  
year:
  id: year_id
  description: year_desc

prc:
  id: prc_id
  first_name: prc_firstName
  method_id: prcMethod_id
  witness_name: prc_witnessName
  semester_id: semester_id
  campus_id: campus_id
  notes: prc_notes
  date: prc_date
  integrated_believer: prc_7upCompleted
  
prcmethod:
  id: prcMethod_id
  description: prcMethod_desc

semester:
  id: semester_id
  description: semester_desc
  start_date: semester_startDate
  year_id: year_id

month:
  id: month_id
  description: month_desc
  number: month_number
  year_id: year_id
  calendar_year: month_calendaryear
  semester_id: semester_id
  
region:
  id: region_id
  description: reg_desc
  country_id: country_id

weeklyreport:
  id: weeklyReport_id
  spiritual_conversations: weeklyReport_1on1SpConv
  gospel_presentations: weeklyReport_1on1GosPres
  holyspirit_presentations: weeklyReport_1on1HsPres
  staff_id: staff_id
  week_id: week_id
  campus_id: campus_id
  followup_completed: weeklyReport_7upCompleted
  spiritual_conversations_student: weeklyReport_1on1SpConvStd
  gospel_presentations_student: weeklyReport_1on1GosPresStd
  holyspirt_presentations_student: weeklyReport_1on1HsPresStd
  followup_completed_student: weeklyReport_7upCompletedStd
  cj_video: weeklyReport_cjVideo
  mda: weeklyReport_mda
  other_evmats: weeklyReport_otherEVMats
  rlk: weeklyReport_rlk
  siq: weeklyReport_siq
  notes: weeklyReport_notes
  
week:
  id: week_id
  end_date: week_endDate
  semester_id: semester_id
  month_id: month_id

country:
  id: country_id
  description: country_desc
  short_description: country_shortDesc

assignment:
  id: assignment_id
  p_id: person_id
  campus_id: campus_id
  status_id: assignmentstatus_id

status:
  id: assignmentstatus_id
  description: assignmentstatus_desc
  
person:
  id: person_id
  first_name: person_fname
  last_name: person_lname
  legal_first_name: person_legal_fname
  legal_last_name: person_legal_lname
  phone: person_phone
  email: person_email
  address: person_addr
  city: person_city
  province_id: province_id
  postal_code: person_pc
  gender_id: gender_id
  local_phone: person_local_phone
  local_address: person_local_addr
  local_city: person_local_city
  local_postal_code: person_local_pc
  local_province_id: person_local_province_id
  cell_phone: cell_phone
  local_valid_until: local_valid_until
  title_id: title_id
  country_id: country_id
  local_country_id: person_local_country_id
  middle_name: person_mname

staff:
  id: staff_id
  person_id: person_id
  is_active: is_active
  
vieweraccessgroup:
  id: vieweraccessgroup_id
  viewer_id: viewer_id
  accessgroup_id: accessgroup_id